##
## Makefile for Arcade in /home/wurmel/rendu/cpp_arcade/lib
##
## Made by Arnaud WURMEL
## Login   <wurmel_a@epitech.net>
##
## Started on  Fri Mar 10 21:12:00 2017 Arnaud WURMEL
## Last update Fri Apr  7 23:18:59 2017 Arnaud WURMEL
##

all:
	make -C ./libsnake/
	make -C ./libsolarfox/
	make -C ./libsokoban/

clean:
	make -C ./libsnake/ clean
	make -C ./libsolarfox/ clean
	make -C ./libsokoban/ clean

fclean:
	make -C ./libsnake/ fclean
	make -C ./libsolarfox/ fclean
	make -C ./libsokoban/ fclean

re:	fclean all
