##
## Makefile for Arcade in /home/wurmel/rendu/cpp_arcade/lib
##
## Made by Arnaud WURMEL
## Login   <wurmel_a@epitech.net>
##
## Started on  Fri Mar 10 21:12:00 2017 Arnaud WURMEL
## Last update Thu Apr  6 14:33:39 2017 Erwan BALLET
##

all:
	make -C ./libsnake/
	make -C ./libsolarfox/

clean:
	make -C ./libsnake/ clean
	make -C ./libsolarfox/ clean

fclean:
	make -C ./libsnake/ fclean
	make -C ./libsolarfox/ fclean

re:	fclean all
